name: cryptbee
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.1.2
  flutter_svg: ^2.0.8
  go_router: ^12.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  jwt_decoder: ^2.0.1
  pinput: ^3.0.1
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^23.1.42
  toast: ^0.3.0
  url_launcher: ^6.1.7
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: assests/background.png
  image: assests/logo/logo.png

flutter_icons:
  android: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assests/logo/icon.png"
  image_path: "assests/logo/icon.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assests/
    - assests/logo/
    - assests/illustrations/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assests/fonts/Poppins-100.ttf
          weight: 100
        - asset: assests/fonts/Poppins-200.ttf
          weight: 200
        - asset: assests/fonts/Poppins-300.ttf
          weight: 300
        - asset: assests/fonts/Poppins-400.ttf
          weight: 400
        - asset: assests/fonts/Poppins-500.ttf
          weight: 500
        - asset: assests/fonts/Poppins-600.ttf
          weight: 600
        - asset: assests/fonts/Poppins-700.ttf
          weight: 700
        - asset: assests/fonts/Poppins-800.ttf
          weight: 800
        - asset: assests/fonts/Poppins-900.ttf
          weight: 900
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
